spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: jinjob-backend-user-service
          uri: lb://jinjob-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: jinjob-backend-question-service
          uri: lb://jinjob-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: jinjob-backend-judge-service
          uri: lb://jinjob-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: jinjob-backend-admin-service
          uri: lb://jinjob-backend-admin-service
          predicates:
            - Path=/api/admin/**
        - id: jinjob-backend-test-service
          uri: lb://jinjob-backend-test-service
          predicates:
            - Path=/api/test/**
  application:
    name: jinjob-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
  servlet:
    context-path: /
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2